package com.cotor.presentation.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.CliktError
import com.github.ajalt.clikt.core.subcommands
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.mordant.terminal.Terminal
import java.nio.file.Files
import kotlin.io.path.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.exists
import kotlin.io.path.writeText

class PluginCommand : CliktCommand(
    name = "plugin",
    help = "Manage Cotor plugins"
) {
    init {
        subcommands(PluginInitCommand())
    }

    override fun run() {
        // container command
    }
}

class PluginInitCommand : CliktCommand(
    name = "init",
    help = "Generate a Kotlin plugin scaffold"
) {
    private val terminal = Terminal()
    private val pluginName by argument("name", help = "Plugin directory name (e.g. my-plugin)")

    override fun run() {
        val root = Path(pluginName)
        if (root.exists()) {
            throw CliktError("Directory already exists: $pluginName")
        }

        createScaffold(root)

        terminal.println("✅ Plugin scaffold created: $pluginName")
        terminal.println("다음 단계:")
        terminal.println("  1) cd $pluginName")
        terminal.println("  2) gradle test")
        terminal.println("  3) gradle jar")
        terminal.println("  4) cotor 실행 시 classpath에 build/libs/*.jar 추가 후 pluginClass 사용")
    }

    private fun createScaffold(root: java.nio.file.Path) {
        val packagePath = "com/example/plugin"
        val mainKotlin = root.resolve("src/main/kotlin/$packagePath")
        val testKotlin = root.resolve("src/test/kotlin/$packagePath")
        val services = root.resolve("src/main/resources/META-INF/services")

        mainKotlin.createDirectories()
        testKotlin.createDirectories()
        services.createDirectories()

        root.resolve("settings.gradle.kts").writeText(
            """
            rootProject.name = "$pluginName"
            """.trimIndent()
        )

        root.resolve("build.gradle.kts").writeText(
            """
            plugins {
                kotlin("jvm") version "2.1.0"
            }

            group = "com.example"
            version = "0.1.0"

            repositories {
                mavenCentral()
            }

            dependencies {
                implementation(files("../build/libs/cotor-1.0.0-all.jar"))
                testImplementation(kotlin("test"))
                testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
            }

            tasks.test {
                useJUnitPlatform()
            }

            kotlin {
                jvmToolchain(17)
            }
            """.trimIndent()
        )

        mainKotlin.resolve("SamplePlugin.kt").writeText(
            """
            package com.example.plugin

            import com.cotor.data.plugin.AgentPlugin
            import com.cotor.data.process.ProcessManager
            import com.cotor.model.AgentMetadata
            import com.cotor.model.AgentParameterSchema
            import com.cotor.model.DataFormat
            import com.cotor.model.ExecutionContext

            class SamplePlugin : AgentPlugin {
                override val metadata: AgentMetadata = AgentMetadata(
                    name = "$pluginName",
                    version = "0.1.0",
                    description = "Sample plugin generated by cotor plugin init",
                    author = "cotor",
                    supportedFormats = listOf(DataFormat.JSON)
                )

                override val parameterSchema: AgentParameterSchema = AgentParameterSchema(emptyList())

                override suspend fun execute(context: ExecutionContext, processManager: ProcessManager): String {
                    val input = context.input ?: ""
                    return "[$pluginName] " + input
                }
            }
            """.trimIndent()
        )

        services.resolve("com.cotor.data.plugin.AgentPlugin").writeText("com.example.plugin.SamplePlugin\n")

        testKotlin.resolve("SamplePluginTest.kt").writeText(
            """
            package com.example.plugin

            import kotlin.test.Test
            import kotlin.test.assertEquals

            class SamplePluginTest {
                @Test
                fun pluginMetadataIsExposed() {
                    val plugin = SamplePlugin()
                    assertEquals("$pluginName", plugin.metadata.name)
                }
            }
            """.trimIndent()
        )

        root.resolve("README.md").writeText(
            """
            # $pluginName

            `cotor plugin init`으로 생성된 Kotlin 플러그인 스캐폴딩입니다.

            ## Build & Test

            ```bash
            gradle test
            gradle jar
            ```

            ## Register in Cotor

            1. 먼저 Cotor 루트에서 `./gradlew shadowJar`로 `build/libs/cotor-1.0.0-all.jar`를 생성합니다.
            2. 생성된 플러그인 jar 경로 확인: `build/libs/$pluginName-0.1.0.jar`
            3. Cotor 실행 시 classpath에 두 jar를 함께 포함합니다.
            4. `cotor.yaml`에서 에이전트 pluginClass를 `com.example.plugin.SamplePlugin`으로 지정합니다.

            ```yaml
            agents:
              - name: my-plugin-agent
                pluginClass: com.example.plugin.SamplePlugin
            ```
            """.trimIndent()
        )

        if (!Files.exists(root.resolve(".gitignore"))) {
            root.resolve(".gitignore").writeText(".gradle\n/build\n")
        }
    }
}
