version: "1.0"

# AI Model Agents
agents:
  - name: claude
    pluginClass: com.cotor.data.plugin.ClaudePlugin
    timeout: 30000
    parameters:
      model: claude-3-opus-20240229
    tags:
      - ai
      - claude
      - anthropic

  - name: codex
    pluginClass: com.cotor.data.plugin.CodexPlugin
    timeout: 30000
    parameters:
      model: gpt-4
    tags:
      - ai
      - openai
      - codex

  - name: copilot
    pluginClass: com.cotor.data.plugin.CopilotPlugin
    timeout: 30000
    tags:
      - ai
      - github
      - copilot

  - name: gemini
    pluginClass: com.cotor.data.plugin.GeminiPlugin
    timeout: 30000
    parameters:
      model: gemini-pro
    tags:
      - ai
      - google
      - gemini

  - name: cursor
    pluginClass: com.cotor.data.plugin.CursorPlugin
    timeout: 30000
    tags:
      - ai
      - cursor

  - name: opencode
    pluginClass: com.cotor.data.plugin.OpenCodePlugin
    timeout: 30000
    tags:
      - ai
      - opencode
      - opensource

# Test Pipelines
pipelines:
  # Test all AI models in parallel
  - name: test-all-models
    description: "Test all AI models simultaneously"
    executionMode: PARALLEL
    stages:
      - id: test-claude
        agent:
          name: claude
          pluginClass: com.cotor.data.plugin.ClaudePlugin
        input: "Generate a hello world function in Python"

      - id: test-codex
        agent:
          name: codex
          pluginClass: com.cotor.data.plugin.CodexPlugin
        input: "Generate a hello world function in JavaScript"

      - id: test-copilot
        agent:
          name: copilot
          pluginClass: com.cotor.data.plugin.CopilotPlugin
        input: "Generate a hello world function in Java"

      - id: test-gemini
        agent:
          name: gemini
          pluginClass: com.cotor.data.plugin.GeminiPlugin
        input: "Generate a hello world function in Go"

      - id: test-cursor
        agent:
          name: cursor
          pluginClass: com.cotor.data.plugin.CursorPlugin
        input: "Generate a hello world function in Rust"

      - id: test-opencode
        agent:
          name: opencode
          pluginClass: com.cotor.data.plugin.OpenCodePlugin
        input: "Generate a hello world function in Kotlin"

  # Test sequential execution
  - name: test-sequential
    description: "Test AI models in sequence"
    executionMode: SEQUENTIAL
    stages:
      - id: claude-generate
        agent:
          name: claude
          pluginClass: com.cotor.data.plugin.ClaudePlugin
        input: "Create a REST API endpoint"

      - id: codex-review
        agent:
          name: codex
          pluginClass: com.cotor.data.plugin.CodexPlugin
        # Input from previous stage

      - id: gemini-optimize
        agent:
          name: gemini
          pluginClass: com.cotor.data.plugin.GeminiPlugin
        # Input from previous stage

  # Test individual models
  - name: test-claude
    description: "Test Claude only"
    executionMode: SEQUENTIAL
    stages:
      - id: claude-test
        agent:
          name: claude
          pluginClass: com.cotor.data.plugin.ClaudePlugin
        input: "Hello Claude! Generate a simple function."

  - name: test-codex
    description: "Test Codex only"
    executionMode: SEQUENTIAL
    stages:
      - id: codex-test
        agent:
          name: codex
          pluginClass: com.cotor.data.plugin.CodexPlugin
        input: "Hello Codex! Generate a simple function."

  - name: test-copilot
    description: "Test Copilot only"
    executionMode: SEQUENTIAL
    stages:
      - id: copilot-test
        agent:
          name: copilot
          pluginClass: com.cotor.data.plugin.CopilotPlugin
        input: "Hello Copilot! Generate a simple function."

  - name: test-gemini
    description: "Test Gemini only"
    executionMode: SEQUENTIAL
    stages:
      - id: gemini-test
        agent:
          name: gemini
          pluginClass: com.cotor.data.plugin.GeminiPlugin
        input: "Hello Gemini! Generate a simple function."

  - name: test-cursor
    description: "Test Cursor only"
    executionMode: SEQUENTIAL
    stages:
      - id: cursor-test
        agent:
          name: cursor
          pluginClass: com.cotor.data.plugin.CursorPlugin
        input: "Hello Cursor! Generate a simple function."

  - name: test-opencode
    description: "Test OpenCode only"
    executionMode: SEQUENTIAL
    stages:
      - id: opencode-test
        agent:
          name: opencode
          pluginClass: com.cotor.data.plugin.OpenCodePlugin
        input: "Hello OpenCode! Generate a simple function."

security:
  useWhitelist: false
  allowedExecutables: []
  allowedDirectories: []

logging:
  level: INFO
  file: cotor-test.log
  format: json

performance:
  maxConcurrentAgents: 10
  coroutinePoolSize: 8
