# This example demonstrates the MAP execution mode, which fans out a stage
# over a list of items. This is useful for applying the same agent to multiple
# inputs in parallel.

# The pipeline has one stage, "fanout-stage", which uses the "file-processor"
# agent. The `fanout` configuration tells the orchestrator to run this stage
# for each item in the "files" list from the shared context.
#
# To run this example, you would need to provide the "files" list in the
# initial context when executing the pipeline.

pipelines:
  - name: "map-execution-example"
    description: "A pipeline demonstrating the MAP execution mode with fanout."
    executionMode: "MAP"
    stages:
      - id: "fanout-stage"
        agent:
          name: "file-processor"
        fanout:
          source: "files" # "files" must be a list in the pipeline's shared context
